=== MovingBlocks/DestinationSol/engine/src/main/resources/assets/schemas/schemaHullConfig.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Describes ship configuration, that is size, health and positions of effect or functional elements. Also describes physical shape of ship.",
  "type": "object",
  "required": [
    "size",
    "maxLife",
    "type",
    "rigidBody",
    "gunSlots"
  ],
  "properties": {
    "size": {
      "type": "number",
      "exclusiveMinimum": 0,
      "description": "Multiplier of ship size in magical units. Common values are between 0.2 (tiny ships) and 5 (huge ships)."
    },
    "maxLife": {
      "type": "integer",
      "description": "Default and maximum achievable life of ship."
    },
    "lightSrcPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Positions of light sources (graphical effect)"
    },
    "forceBeaconPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Beacons - things on ships and stations that attract other ships from close enough range ('docking ports')"
    },
    "doorPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Positions of door centers on ships - doors are horizontal things opening on other ship proximity."
    },
    "type": {
      "type": "string",
      "enum": [
        "std",
        "big",
        "station"
      ],
      "description": "Denotes whether ship is standard or big size, or if it is a station"
    },
    "engine": {
      "type": "string",
      "description": "Id of the engine on the ship",
      "pattern": "^\\w+:\\w+$"
    },
    "ability": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Type of ship's ability - one of 'sloMo', 'knockBack', 'teleport', 'emWave', 'unShield'"
        },
        "rechargeTime": {
          "type": "number",
          "minimum": 0,
          "description": "Recharge time of ability in seconds."
        }
      },
      "anyOf": [
        {
          "properties": {
            "type": {
              "enum": [
                "sloMo"
              ]
            },
            "factor": {
              "type": "number",
              "description": "Multiplier of time speed - 1 is normal speed, lower values slow down time, higher speed up time."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "teleport"
              ]
            },
            "angle": {
              "type": "number"
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "knockBack"
              ]
            },
            "force": {
              "type": "number",
              "description": "Denotes how hard everything within radius is pushed away."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "emWave"
              ]
            },
            "duration": {
              "type": "number",
              "description": "For how long controls of ships in range will be disabled, in seconds."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "unShield"
              ]
            },
            "amount": {
              "type": "number",
              "description": "Damage to deal to enemy shields."
            }
          }
        }
      ]
    },
    "displayName": {
      "type": "string",
      "description": "Human friendly name of the ship"
    },
    "price": {
      "type": "number",
      "description": "Price for buying this ship in shop"
    },
    "hirePrice": {
      "type": "number",
      "description": "Price for hiring this ship as mercenary"
    },
    "rigidBody": {
      "description": "Physical model of ship's body. This is meant to be exported from some utility application (b2dEditor",
      "type": "object",
      "properties": {
        "origin": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ]
        },
        "polygons": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "x": {
                  "type": "number"
                },
                "y": {
                  "type": "number"
                }
              }
            }
          }
        },
        "shapes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              }
            }
          }
        },
        "circles": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "cx": {
                "type": "number"
              },
              "cy": {
                "type": "number"
              },
              "r": {
                "type": "number"
              }
            }
          }
        }
      },
      "required": [
        "origin",
        "polygons",
        "shapes",
        "circles"
      ]
    },
    "gunSlots": {
      "type": "array",
      "items": {
        "type": "object",
        "minItems": 1,
        "maxItems": 2,
        "properties": {
          "position": {
            "$ref": "#/definitions/vec2"
          },
          "isUnderneathHull": {
            "type": "boolean"
          },
          "allowsRotation": {
            "type": "boolean"
          }
        },
        "required": [
          "position"
        ]
      }
    },
    "particleEmitters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "position": {
            "$ref": "#/definitions/vec2"
          },
          "trigger": {
            "type": "string"
          },
          "angleOffset": {
            "type": "number"
          },
          "hasLight": {
            "type": "boolean"
          },
          "particle": {
            "type": "object",
            "required": [
              "effectFile",
              "tex",
              "tint"
            ],
            "properties": {
              "effectFile": {
                "type": "string",
                "pattern": "^\\w+:\\w+$"
              },
              "size": {
                "type": "number"
              },
              "tex": {
                "type": "string",
                "pattern": "^\\w+:\\w+$"
              },
              "floatsUp": {
                "type": "boolean"
              },
              "tint": {
                "type": "string",
                "pattern": "^(\\w+|(hsb (((360)|(3[0-5]\\d)|([012]?\\d?\\d))( ((100)|\\d?\\d)){2})|(((([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5])) ){2}(([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5]))))( (([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5])))?)$"
              }
            }
          },
          "workSounds": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^\\w+:\\w+$"
            }
          }
        },
        "required": [
          "position",
          "trigger",
          "particle"
        ]
      }
    }
  },
  "definitions": {
    "vec2": {
      "type": "string",
      "pattern": "^(([0-9]*\\.)?[0-9]+ +([0-9]*\\.)?[0-9]+)$",
      "$comment": "2 float values separated by one or more spaces, ints also accepted"
    },
    "vec2List": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/vec2"
      }
    }
  }
}

=== MovingBlocks/DestinationSol/modules/tribe/assets/ships/serenityStation/serenityStation.json
{
  "size": 10,
  "maxLife": 1000,
  "type": "station",
  "gunSlots": [
    {
      "position": "0.080078125 0.5234375",
      "isUnderneathHull": false,
      "allowsRotation": true
    },
    {
      "position": "0.91796875 0.5234375",
      "isUnderneathHull": false,
      "allowsRotation": true
    }
  ],
  "lightSrcPoss": [
    "0.080078125 0.5234375",
    "0.91796875 0.5234375"
  ],
  "forceBeaconPoss": [
    "0.26171875 0.498046875",
    "0.759765625 0.498046875"
  ],
  "rigidBody": {
    "origin": {
      "x": 0.5,
      "y": 0.5
    },
    "polygons": [],
    "circles": [
      {
        "cx": 0.5079167485237122,
        "cy": 0.46166640520095825,
        "r": 0.20926126837730408
      },
      {
        "cx": 0.3097917139530182,
        "cy": 0.438958078622818,
        "r": 0.06629715114831924
      },
      {
        "cx": 0.5935417413711548,
        "cy": 0.30395811796188354,
        "r": 0.05857690051198006
      },
      {
        "cx": 0.39229172468185425,
        "cy": 0.3414580821990967,
        "r": 0.06434766203165054
      }
    ],
    "shapes": [
      {
        "type": "CIRCLE",
        "vertices": [
          {
            "x": 0.5079167485237122,
            "y": 0.46166640520095825
          },
          {
            "x": 0.6187500953674316,
            "y": 0.2841663956642151
          }
        ]
      },
      {
        "type": "CIRCLE",
        "vertices": [
          {
            "x": 0.3097917139530182,
            "y": 0.438958078622818
          },
          {
            "x": 0.35604172945022583,
            "y": 0.39145809412002563
          }
        ]
      },
      {
        "type": "CIRCLE",
        "vertices": [
          {
            "x": 0.5935417413711548,
            "y": 0.30395811796188354
          },
          {
            "x": 0.6385417580604553,
            "y": 0.26645809412002563
          }
        ]
      },
      {
        "type": "CIRCLE",
        "vertices": [
          {
            "x": 0.39229172468185425,
            "y": 0.3414580821990967
          },
          {
            "x": 0.42354172468185425,
            "y": 0.2852081060409546
          }
        ]
      }
    ]
  }
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/imperialCapital/imperialCapital.json
{
    "size": 3.5,
    "maxLife": 800,
    "type": "big",
    "price": 20000,
    "displayName": "Imperial Capital Ship",
    "engine": "core:imperialBigEngine",
    "gunSlots": [
        {
            "position": "0.276 0.2935",
            "isUnderneathHull": false,
            "allowsRotation": true
        },
        {
            "position": "0.276 0.7075",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "rigidBody": {
       "origin":{"x":0.51624995470047,"y":0.5012499690055847},"polygons":[[{"x":0.1199999749660492,"y":0.4350000023841858},{"x":0.05249994993209839,"y":0.3700000047683716},{"x":0.27000001072883606,"y":0.1799999475479126}],[{"x":0.27000001072883606,"y":0.1799999475479126},{"x":0.9925000667572021,"y":0.4675000011920929},{"x":0.11749997735023499,"y":0.5550000071525574},{"x":0.1199999749660492,"y":0.4350000023841858}],[{"x":0.9925000667572021,"y":0.4675000011920929},{"x":0.9900000095367432,"y":0.5400000214576721},{"x":0.27000001072883606,"y":0.8125},{"x":0.06499996781349182,"y":0.6424999833106995},{"x":0.11749997735023499,"y":0.5550000071525574}]],"circles":[],"shapes":[{"type":"POLYGON","vertices":[{"x":0.9900000095367432,"y":0.5400000214576721},{"x":0.27000001072883606,"y":0.8125},{"x":0.06499996781349182,"y":0.6424999833106995},{"x":0.11749997735023499,"y":0.5550000071525574},{"x":0.1199999749660492,"y":0.4350000023841858},{"x":0.05249994993209839,"y":0.3700000047683716},{"x":0.27000001072883606,"y":0.1799999475479126},{"x":0.9925000667572021,"y":0.4675000011920929}]}]
    },
    "particleEmitters": [
        {
            "position": "0.08 0.37",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.3,
                "tex": "core:fire",
                "tint": "hsb 140 20 65"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        },
        {
            "position": "0.08 0.63",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.3,
                "tex": "core:fire",
                "tint": "hsb 140 20 65"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        }
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/desertPlanetTurret/desertPlanetTurretProperties.json
{
    "size": 0.8,
    "maxLife": 46,
    "type": "station",
    "gunSlots": [
        {
            "position": "0.51 0.21",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "rigidBody": {
        "origin": {
            "x": 0.5199999809265137,
            "y": 0.6737500429153442
        },
        "polygons": [
            [
                {
                    "x": 0.7599999904632568,
                    "y": 0.26375001668930054
                },
                {
                    "x": 0.5227272510528564,
                    "y": 0.7443181276321411
                },
                {
                    "x": 0.2800000309944153,
                    "y": 0.2562500536441803
                }
            ],
            [
                {
                    "x": 0.5227272510528564,
                    "y": 0.36174243688583374
                },
                {
                    "x": 0.6287879347801208,
                    "y": 0.8996212482452393
                },
                {
                    "x": 0.39772728085517883,
                    "y": 0.9071969389915466
                }
            ]
        ],
        "circles": [
        ],
        "shapes": [
            {
                "type": "POLYGON",
                "vertices": [
                    {
                        "x": 0.2800000309944153,
                        "y": 0.2562500536441803
                    },
                    {
                        "x": 0.5227272510528564,
                        "y": 0.7443181276321411
                    },
                    {
                        "x": 0.7599999904632568,
                        "y": 0.26375001668930054
                    }
                ]
            },
            {
                "type": "POLYGON",
                "vertices": [
                    {
                        "x": 0.39772728085517883,
                        "y": 0.9071969389915466
                    },
                    {
                        "x": 0.6287879347801208,
                        "y": 0.8996212482452393
                    },
                    {
                        "x": 0.5227272510528564,
                        "y": 0.36174243688583374
                    }
                ]
            }
        ]
    }
}

=== MovingBlocks/DestinationSol/modules/kree/assets/ships/kreeLarge/kreeLarge.json
{
    "size": 1,
    "maxLife": 80,
    "type": "std",
    "price": 2000,
    "ability": {
        "type": "sloMo",
        "factor": 0.3,
        "rechargeTime": 5
    },
    "displayName": "empireguard",
    "engine": "core:imperialEngine",
    "gunSlots": [
        {
            "position": "0.54 0.10",
            "isUnderneathHull": false,
            "allowsRotation": false
        },
        {
            "position": "0.54 0.74",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "rigidBody": {"name":"lship","imagePath":"../DestinationSol/modules/empire/assets/ships/empireLarge/empireLarge.png","origin":{"x":0.5,"y":0.5},
        "polygons":[[{"x":0.0625,"y":0.75},{"x":0.01171875,"y":0.75390625},{"x":0,"y":0.66015625},{"x":0.07524425536394119,"y":0.7243351936340332}],[{"x":0.1328125,"y":0.7734375},{"x":0.0703125,"y":0.77734375},{"x":0.0625,"y":0.75},{"x":0.07524425536394119,"y":0.7243351936340332}],[{"x":0,"y":0.66015625},{"x":0.01171875,"y":0.6171875},{"x":0.19140625,"y":0.79296875},{"x":0.1328125,"y":0.7734375}],[{"x":0.0703125,"y":0.51171875},{"x":0.078125,"y":0.48828125},{"x":0.17578125,"y":0.48046875},{"x":0.2265625,"y":0.82421875},{"x":0.19140625,"y":0.79296875}],[{"x":0.19140625,"y":0.79296875},{"x":0.01171875,"y":0.6171875},{"x":0,"y":0.56640625},{"x":0.0078125,"y":0.51171875},{"x":0.0703125,"y":0.51171875}],[{"x":0.1796875,"y":0.32421875},{"x":0.06640625,"y":0.2890625},{"x":0.078125,"y":0.27734375},{"x":0.3359375,"y":0.265625},{"x":0.59765625,"y":0.2734375}],[{"x":0.59765625,"y":0.2734375},{"x":0.734375,"y":0.296875},{"x":0.8203125,"y":0.328125},{"x":0.80859375,"y":0.33984375},{"x":0.67578125,"y":0.34375},{"x":0.1796875,"y":0.32421875}],[{"x":0.67578125,"y":0.34375},{"x":0.6328125,"y":0.375},{"x":0.23828125,"y":0.36328125},{"x":0.1796875,"y":0.32421875}],[{"x":0.6328125,"y":0.375},{"x":0.61328125,"y":0.4140625},{"x":0.23828125,"y":0.41015625},{"x":0.23828125,"y":0.36328125}],[{"x":0.859375,"y":0.453125},{"x":0.9921875,"y":0.50390625},{"x":0.828125,"y":0.50390625}],[{"x":0.828125,"y":0.50390625},{"x":0.80859375,"y":0.51953125},{"x":0.70703125,"y":0.51953125},{"x":0.67578125,"y":0.50390625},{"x":0.70703125,"y":0.43359375},{"x":0.77734375,"y":0.41796875},{"x":0.84375,"y":0.4296875},{"x":0.859375,"y":0.453125}],[{"x":0.67578125,"y":0.50390625},{"x":0.59375,"y":0.5078125},{"x":0.62109375,"y":0.4296875},{"x":0.70703125,"y":0.43359375}],[{"x":0.59375,"y":0.5078125},{"x":0.21484375,"y":0.453125},{"x":0.23828125,"y":0.41015625},{"x":0.61328125,"y":0.4140625},{"x":0.62109375,"y":0.4296875}],[{"x":0.7265625,"y":0.59765625},{"x":0.77734375,"y":0.62890625},{"x":0.76171875,"y":0.65625},{"x":0.72265625,"y":0.671875}],[{"x":0.72265625,"y":0.671875},{"x":0.66015625,"y":0.55859375},{"x":0.7265625,"y":0.578125},{"x":0.7265625,"y":0.59765625}],[{"x":0.66015625,"y":0.70703125},{"x":0.59375,"y":0.7421875},{"x":0.23828125,"y":0.86328125},{"x":0.2265625,"y":0.82421875},{"x":0.17578125,"y":0.48046875},{"x":0.21484375,"y":0.453125},{"x":0.59375,"y":0.5078125},{"x":0.66015625,"y":0.55859375}],[{"x":0.66015625,"y":0.55859375},{"x":0.72265625,"y":0.671875},{"x":0.703125,"y":0.703125},{"x":0.66015625,"y":0.70703125}],[{"x":0.83984375,"y":0.76171875},{"x":0.98046875,"y":0.76171875},{"x":0.9453125,"y":0.7890625},{"x":0.76953125,"y":0.84765625}],[{"x":0.76953125,"y":0.84765625},{"x":0.71484375,"y":0.84765625},{"x":0.69140625,"y":0.83203125},{"x":0.68359375,"y":0.76171875},{"x":0.70703125,"y":0.74609375},{"x":0.8125,"y":0.74609375},{"x":0.83984375,"y":0.76171875}],[{"x":0.69140625,"y":0.83203125},{"x":0.62109375,"y":0.8359375},{"x":0.62109375,"y":0.76171875},{"x":0.68359375,"y":0.76171875}],[{"x":0.62109375,"y":0.8359375},{"x":0.61328125,"y":0.8515625},{"x":0.2265625,"y":0.921875},{"x":0.23828125,"y":0.86328125},{"x":0.59375,"y":0.7421875},{"x":0.62109375,"y":0.76171875}],[{"x":0.71484375,"y":0.92578125},{"x":0.828125,"y":0.92578125},{"x":0.80078125,"y":0.94921875},{"x":0.6953125,"y":0.9765625}],[{"x":0.6953125,"y":0.9765625},{"x":0.52734375,"y":0.99609375},{"x":0.6484375,"y":0.90625},{"x":0.71484375,"y":0.92578125}],[{"x":0.52734375,"y":0.99609375},{"x":0.296875,"y":1},{"x":0.07421875,"y":0.98828125},{"x":0.08203125,"y":0.97265625},{"x":0.2265625,"y":0.921875},{"x":0.61328125,"y":0.8515625},{"x":0.6484375,"y":0.90625}]],"circles":[],"shapes":[{"type":"POLYGON","vertices":[{"x":0.296875,"y":1},{"x":0.52734375,"y":0.99609375},{"x":0.6953125,"y":0.9765625},{"x":0.80078125,"y":0.94921875},{"x":0.828125,"y":0.92578125},{"x":0.71484375,"y":0.92578125},{"x":0.6484375,"y":0.90625},{"x":0.61328125,"y":0.8515625},{"x":0.62109375,"y":0.8359375},{"x":0.69140625,"y":0.83203125},{"x":0.71484375,"y":0.84765625},{"x":0.76953125,"y":0.84765625},{"x":0.9453125,"y":0.7890625},{"x":0.98046875,"y":0.76171875},{"x":0.83984375,"y":0.76171875},{"x":0.8125,"y":0.74609375},{"x":0.70703125,"y":0.74609375},{"x":0.68359375,"y":0.76171875},{"x":0.62109375,"y":0.76171875},{"x":0.59375,"y":0.7421875},{"x":0.66015625,"y":0.70703125},{"x":0.703125,"y":0.703125},{"x":0.72265625,"y":0.671875},{"x":0.76171875,"y":0.65625},{"x":0.77734375,"y":0.62890625},{"x":0.7265625,"y":0.59765625},{"x":0.7265625,"y":0.578125},{"x":0.66015625,"y":0.55859375},{"x":0.59375,"y":0.5078125},{"x":0.67578125,"y":0.50390625},{"x":0.70703125,"y":0.51953125},{"x":0.80859375,"y":0.51953125},{"x":0.828125,"y":0.50390625},{"x":0.9921875,"y":0.50390625},{"x":0.859375,"y":0.453125},{"x":0.84375,"y":0.4296875},{"x":0.77734375,"y":0.41796875},{"x":0.70703125,"y":0.43359375},{"x":0.62109375,"y":0.4296875},{"x":0.61328125,"y":0.4140625},{"x":0.6328125,"y":0.375},{"x":0.67578125,"y":0.34375},{"x":0.80859375,"y":0.33984375},{"x":0.8203125,"y":0.328125},{"x":0.734375,"y":0.296875},{"x":0.59765625,"y":0.2734375},{"x":0.3359375,"y":0.26562},{"x":0.078125,"y":0.27734375},{"x":0.06640625,"y":0.2890625},{"x":0.1796875,"y":0.32421875},{"x":0.23828125,"y":0.36328125},{"x":0.23828125,"y":0.41015625},{"x":0.21484375,"y":0.453125},{"x":0.17578125,"y":0.48046875},{"x":0.078125,"y":0.48828125},{"x":0.0703125,"y":0.51171875},{"x":0.0078125,"y":0.51171875},{"x":0,"y":0.56640625},{"x":0.01171875,"y":0.6171875},{"x":0,"y":0.66015625},{"x":0.01171875,"y":0.75390625},{"x":0.0625,"y":0.75},{"x":0.0703125,"y":0.77734375},{"x":0.1328125,"y":0.7734375},{"x":0.19140625,"y":0.79296875},{"x":0.2265625,"y":0.82421875},{"x":0.23828125,"y":0.86328125},{"x":0.2265625,"y":0.921875},{"x":0.08203125,"y":0.97265625},{"x":0.07421875,"y":0.98828125}]}]},
    "particleEmitters": [
        {
            "position": "0.11 0.41",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:fire",
                "tint": "hsb 140 20 65"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        },
        {
            "position": "0.11 0.41",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:fire",
                "tint": "hsb 140 20 65"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        }
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/imperialBig/imperialBig.json
{
    "size": 1,
    "maxLife": 80,
    "type": "std",
    "price": 2000,
    "ability": {
        "type": "sloMo",
        "factor": 0.3,
        "rechargeTime": 5
    },
    "displayName": "Vanguard",
    "engine": "core:imperialEngine",
    "gunSlots": [
        {
            "position": "0.54 0.26",
            "isUnderneathHull": false,
            "allowsRotation": false
        },
        {
            "position": "0.54 0.74",
            "isUnderneathHull": false,
            "allowsRotation": false
        }
    ],
    "rigidBody": {
      "origin":{"x":0.5524998307228088,"y":0.4962499141693115},"polygons":[[{"x":0.9300000667572021,"y":0.4975000023841858},{"x":0.5324999690055847,"y":0.8424999713897705},{"x":0.09499996900558472,"y":0.7925000190734863},{"x":0.054999977350234985,"y":0.5024999380111694},{"x":0.09249997138977051,"y":0.19749996066093445},{"x":0.5399999618530273,"y":0.15999996662139893}]],"circles":[],"shapes":[{"type":"POLYGON","vertices":[{"x":0.9300000667572021,"y":0.4975000023841858},{"x":0.5324999690055847,"y":0.8424999713897705},{"x":0.09499996900558472,"y":0.7925000190734863},{"x":0.054999977350234985,"y":0.5024999380111694},{"x":0.09249997138977051,"y":0.19749996066093445},{"x":0.5399999618530273,"y":0.15999996662139893}]}]
    },
    "particleEmitters": [
        {
            "position": "0.11 0.43",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:fire",
                "tint": "hsb 140 20 65"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        },
        {
            "position": "0.11 0.57",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:fire",
                "tint": "hsb 140 20 65"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        }
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/desertSpaceTurret/desertSpaceTurret.json
{
    "size": 1.2,
    "maxLife": 75,
    "type": "std",
    "gunSlots": [
        {
            "position": "0.38 0.43",
            "isUnderneathHull": false,
            "allowsRotation": true
        },
        {
            "position": "0.62 0.57",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "lightSrcPoss": [
        ".1 .5",
        ".9 .5"
    ],
    "rigidBody": {
     "origin":{"x":0.4925000071525574,"y":0.5},"polygons":[[{"x":0.029999971389770508,"y":0.574999988079071},{"x":0.029999971389770508,"y":0.41999998688697815},{"x":0.3174999952316284,"y":0.13499996066093445},{"x":0.6700000762939453,"y":0.13249999284744263},{"x":0.9599999785423279,"y":0.42499998211860657},{"x":0.9625000357627869,"y":0.5674999952316284},{"x":0.6574999690055847,"y":0.8774999976158142},{"x":0.3174999952316284,"y":0.8774999976158142}]],"circles":[],"shapes":[{"type":"POLYGON","vertices":[{"x":0.3174999952316284,"y":0.8774999976158142},{"x":0.6574999690055847,"y":0.8774999976158142},{"x":0.9625000357627869,"y":0.5674999952316284},{"x":0.9599999785423279,"y":0.42499998211860657},{"x":0.6700000762939453,"y":0.13249999284744263},{"x":0.3174999952316284,"y":0.13499996066093445},{"x":0.029999971389770508,"y":0.41999998688697815},{"x":0.029999971389770508,"y":0.574999988079071}]}]
    }
}
