=== MovingBlocks/DestinationSol/engine/src/main/resources/assets/schemas/schemaGun.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Guns are the primary weapons for ships",
  "type": "object",
  "required": [
    "maxAngleVar",
    "angleVarDamp",
    "angleVarPerShot",
    "timeBetweenShots",
    "reloadTime",
    "price",
    "clipName",
    "gunLength",
    "displayName",
    "shootSounds",
    "reloadSounds"
  ],
  "properties": {
    "maxAngleVar": {
      "type": "integer",
      "minimum": 0,
      "description": "Maximum angle variation for a shot from the center of the gun"
    },
    "angleVarDamp": {
      "type": "integer",
      "minimum": 0,
      "description": "Puts a damper or delay on the angle variation"
    },
    "angleVarPerShot": {
      "type": "integer",
      "minimum": 0,
      "description": "Controls how much the angle of the bullet can vary from shot to shot"
    },
    "timeBetweenShots": {
      "type": "number",
      "minimum": 0,
      "description": "Controls how fast the gun fires"
    },
    "reloadTime": {
      "type": "number",
      "minimum": 0,
      "description": "Amount of time in seconds it takes for the gun to reload"
    },
    "price": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "description": "Amount the gun costs to buy at a station"
    },
    "clipName": {
      "type": "string",
      "pattern": "^\\w+:\\w+$",
      "description": "Module path of the clip the gun uses to fire"
    },
    "gunLength": {
      "type": "number",
      "exclusiveMinimum": 0,
      "description": "Multiplier used to scale the gun length"
    },
    "displayName": {
      "type": "string",
      "minLength": 1,
      "description": "Name to be displayed in inventories and trading stations"
    },
    "shootSounds": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\w+:\\w+$"
      },
      "description": "An array to iterate over when firing the gun for audio assets to be played"
    },
    "reloadSounds": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\w+:\\w+$"
      },
      "description": "An array to iterate over when reloading the gun for audio assets to be played"
    },
    "fixed": {
      "type": "boolean",
      "description": "Controls whether the gun is fixed in place"
    },
    "texLenPerc": {
      "type": "number",
      "description": "Multiplier to scale the length of the projetile's texture"
    },
    "lightOnShot": {
      "type": "boolean",
      "description": "Whether the gun should show a light at the muzzle when it fires"
    }
  }
}

=== MovingBlocks/DestinationSol/modules/core/assets/items/guns/fixedBlaster/fixedBlaster.json
{
    "fixed": true,
    "maxAngleVar": 10,
    "angleVarDamp": 6,
    "angleVarPerShot": 1,
    "timeBetweenShots": 0.1,
    "reloadTime": 3,
    "price": 500,
    "clipName": "core:blasterClip",
    "gunLength": 0.24,
    "displayName": "Heavy Blaster",
    "lightOnShot": true,
    "shootSounds": [
        "core:blasterShoot"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/caution/assets/items/guns/heartAttack/heartAttack.json
{
    "maxAngleVar": 10,
    "angleVarDamp": 6,
    "angleVarPerShot": 2,
    "timeBetweenShots": 0.1,
    "reloadTime": 0.5,
    "price": 800,
    "clipName": "caution:rbcClip",
    "gunLength": 0.14,
    "displayName": "RBC Machine Gun",
    "lightOnShot": true,
    "shootSounds": [
        "core:waveGun"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/rebel/assets/items/guns/Destroyer/destroyerGun.json
{
  "fixed": true,
  "maxAngleVar": 10,
  "angleVarDamp": 6,
  "angleVarPerShot": 1,
  "timeBetweenShots": 0.07,
  "reloadTime": 2,
  "price": 220,
  "clipName": "rebel:rebelXClip",
  "gunLength": 0.18,
  "displayName": "Destroyer",
  "lightOnShot": true,
  "shootSounds": [
    "core:fixedGunShoot0",
    "core:fixedGunShoot1"
  ],
  "reloadSounds": [
    "core:fixedGunReload"
  ]
}

=== MovingBlocks/DestinationSol/modules/tribe/assets/items/guns/laser/laser.json
{
  "fixed": false,
  "maxAngleVar": 0,
  "angleVarDamp": 0,
  "angleVarPerShot": 0,
  "timeBetweenShots": -10,
  "reloadTime": 0.1,
  "price": 1000000,
  "clipName": "tribe:laserClip",
  "gunLength": 0.5,
  "displayName": "Laser",
  "lightOnShot": true,
  "shootSounds": [
    "core:waveGun"
  ],
  "reloadSounds": [
    "core:gunReload"
  ]
}

=== MovingBlocks/DestinationSol/modules/draconic/assets/items/guns/scorcher/scorcher.json
{
  "fixed": true,
  "maxAngleVar": 15,
  "angleVarDamp": 5,
  "angleVarPerShot": 4,
  "timeBetweenShots": 1.0,
  "reloadTime": 2.0,
  "price": 250,
  "clipName": "draconic:fireballClip",
  "gunLength": 0.25,
  "texLenPerc": 0.87,
  "displayName": "Scorcher",
  "shootSounds": [
    "core:shotGunShoot"
  ],
  "reloadSounds": [
    "core:gunReload"
  ]
}

=== MovingBlocks/DestinationSol/modules/syndicate/assets/items/guns/bazook/bazook.json
{
  "fixed": true,
  "maxAngleVar": 0,
  "angleVarDamp": 10,
  "angleVarPerShot": 1,
  "timeBetweenShots": 0.02,
  "reloadTime": 5,
  "price": 5000,
  "clipName": "syndicate:bazookClip",
  "gunLength": 0.2,
  "displayName": "Bazook",
  "lightOnShot": true,
  "shootSounds": [
    "core:rocketLauncherShoot"
  ],
  "reloadSounds": [
    "core:rocketLauncherReload"
  ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/items/guns/blaster/blaster.json
{
    "maxAngleVar": 30,
    "angleVarDamp": 6,
    "angleVarPerShot": 2,
    "timeBetweenShots": 0.9,
    "reloadTime": 3,
    "price": 50,
    "clipName": "core:blasterClip",
    "gunLength": 0.14,
    "displayName": "Blaster",
    "lightOnShot": true,
    "shootSounds": [
        "core:blasterShoot"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/items/guns/emGun/emGun.json
{
    "maxAngleVar": 30,
    "angleVarDamp": 6,
    "angleVarPerShot": 2,
    "timeBetweenShots": 0,
    "reloadTime": 3.5,
    "price": 750,
    "clipName": "core:emClip",
    "gunLength": 0.2,
    "texLenPerc": 0.85,
    "displayName": "EM Gun",
    "lightOnShot": true,
    "shootSounds": [
        "core:emGun"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}
