=== MovingBlocks/DestinationSol/engine/src/main/resources/assets/schemas/schemaHullConfig.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Describes ship configuration, that is size, health and positions of effect or functional elements. Also describes physical shape of ship.",
  "type": "object",
  "required": [
    "size",
    "maxLife",
    "type",
    "rigidBody",
    "gunSlots"
  ],
  "properties": {
    "size": {
      "type": "number",
      "exclusiveMinimum": 0,
      "description": "Multiplier of ship size in magical units. Common values are between 0.2 (tiny ships) and 5 (huge ships)."
    },
    "maxLife": {
      "type": "integer",
      "description": "Default and maximum achievable life of ship."
    },
    "lightSrcPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Positions of light sources (graphical effect)"
    },
    "forceBeaconPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Beacons - things on ships and stations that attract other ships from close enough range ('docking ports')"
    },
    "doorPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Positions of door centers on ships - doors are horizontal things opening on other ship proximity."
    },
    "type": {
      "type": "string",
      "enum": [
        "std",
        "big",
        "station"
      ],
      "description": "Denotes whether ship is standard or big size, or if it is a station"
    },
    "engine": {
      "type": "string",
      "description": "Id of the engine on the ship",
      "pattern": "^\\w+:\\w+$"
    },
    "ability": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Type of ship's ability - one of 'sloMo', 'knockBack', 'teleport', 'emWave', 'unShield'"
        },
        "rechargeTime": {
          "type": "number",
          "minimum": 0,
          "description": "Recharge time of ability in seconds."
        }
      },
      "anyOf": [
        {
          "properties": {
            "type": {
              "enum": [
                "sloMo"
              ]
            },
            "factor": {
              "type": "number",
              "description": "Multiplier of time speed - 1 is normal speed, lower values slow down time, higher speed up time."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "teleport"
              ]
            },
            "angle": {
              "type": "number"
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "knockBack"
              ]
            },
            "force": {
              "type": "number",
              "description": "Denotes how hard everything within radius is pushed away."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "emWave"
              ]
            },
            "duration": {
              "type": "number",
              "description": "For how long controls of ships in range will be disabled, in seconds."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "unShield"
              ]
            },
            "amount": {
              "type": "number",
              "description": "Damage to deal to enemy shields."
            }
          }
        }
      ]
    },
    "displayName": {
      "type": "string",
      "description": "Human friendly name of the ship"
    },
    "price": {
      "type": "number",
      "description": "Price for buying this ship in shop"
    },
    "hirePrice": {
      "type": "number",
      "description": "Price for hiring this ship as mercenary"
    },
    "rigidBody": {
      "description": "Physical model of ship's body. This is meant to be exported from some utility application (b2dEditor",
      "type": "object",
      "properties": {
        "origin": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ]
        },
        "polygons": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "x": {
                  "type": "number"
                },
                "y": {
                  "type": "number"
                }
              }
            }
          }
        },
        "shapes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              }
            }
          }
        },
        "circles": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "cx": {
                "type": "number"
              },
              "cy": {
                "type": "number"
              },
              "r": {
                "type": "number"
              }
            }
          }
        }
      },
      "required": [
        "origin",
        "polygons",
        "shapes",
        "circles"
      ]
    },
    "gunSlots": {
      "type": "array",
      "items": {
        "type": "object",
        "minItems": 1,
        "maxItems": 2,
        "properties": {
          "position": {
            "$ref": "#/definitions/vec2"
          },
          "isUnderneathHull": {
            "type": "boolean"
          },
          "allowsRotation": {
            "type": "boolean"
          }
        },
        "required": [
          "position"
        ]
      }
    },
    "particleEmitters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "position": {
            "$ref": "#/definitions/vec2"
          },
          "trigger": {
            "type": "string"
          },
          "angleOffset": {
            "type": "number"
          },
          "hasLight": {
            "type": "boolean"
          },
          "particle": {
            "type": "object",
            "required": [
              "effectFile",
              "tex",
              "tint"
            ],
            "properties": {
              "effectFile": {
                "type": "string",
                "pattern": "^\\w+:\\w+$"
              },
              "size": {
                "type": "number"
              },
              "tex": {
                "type": "string",
                "pattern": "^\\w+:\\w+$"
              },
              "floatsUp": {
                "type": "boolean"
              },
              "tint": {
                "type": "string",
                "pattern": "^(\\w+|(hsb (((360)|(3[0-5]\\d)|([012]?\\d?\\d))( ((100)|\\d?\\d)){2})|(((([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5])) ){2}(([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5]))))( (([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5])))?)$"
              }
            }
          },
          "workSounds": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^\\w+:\\w+$"
            }
          }
        },
        "required": [
          "position",
          "trigger",
          "particle"
        ]
      }
    }
  },
  "definitions": {
    "vec2": {
      "type": "string",
      "pattern": "^(([0-9]*\\.)?[0-9]+ +([0-9]*\\.)?[0-9]+)$",
      "$comment": "2 float values separated by one or more spaces, ints also accepted"
    },
    "vec2List": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/vec2"
      }
    }
  }
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/pirateOrbiter/pirateOrbiter.json
{
    "size": 0.76,
    "maxLife": 26,
    "type": "std",
    "price": 300,
    "ability": {
        "type": "unShield",
        "amount": 8,
        "rechargeTime": 7
    },
    "displayName": "Orbiter",
    "engine": "core:pirateEngine",
    "gunSlots": [
        {
            "position": "0.47 0.39",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "rigidBody": {
       "origin":{"x":0.5113636255264282,"y":0.4943181574344635},"polygons":[[{"x":0.5874999761581421,"y":0.7124999761581421},{"x":0.565000057220459,"y":0.8575000166893005},{"x":0.4000000059604645,"y":0.8550000190734863},{"x":0.39249998331069946,"y":0.7000000476837158}],[{"x":0.4125000238418579,"y":0.28749996423721313},{"x":0.41499996185302734,"y":0.13499996066093445},{"x":0.512499988079071,"y":0.12250000238418579},{"x":0.5225000381469727,"y":0.29249995946884155}],[{"x":0.5225000381469727,"y":0.29249995946884155},{"x":0.6100000143051147,"y":0.3024999797344208},{"x":0.6549999713897705,"y":0.4424999952316284},{"x":0.3374999761581421,"y":0.49000000953674316},{"x":0.3174999952316284,"y":0.3424999713897705},{"x":0.4125000238418579,"y":0.28749996423721313}],[{"x":0.6549999713897705,"y":0.4424999952316284},{"x":0.8299999833106995,"y":0.5900000333786011},{"x":0.6600000262260437,"y":0.7024999856948853},{"x":0.5874999761581421,"y":0.7124999761581421},{"x":0.39249998331069946,"y":0.7000000476837158},{"x":0.22749999165534973,"y":0.6200000047683716},{"x":0.23749998211860657,"y":0.5249999761581421},{"x":0.3374999761581421,"y":0.49000000953674316}]],"circles":[],"shapes":[{"type":"POLYGON","vertices":[{"x":0.8299999833106995,"y":0.5900000333786011},{"x":0.6600000262260437,"y":0.7024999856948853},{"x":0.5874999761581421,"y":0.7124999761581421},{"x":0.565000057220459,"y":0.8575000166893005},{"x":0.4000000059604645,"y":0.8550000190734863},{"x":0.39249998331069946,"y":0.7000000476837158},{"x":0.22749999165534973,"y":0.6200000047683716},{"x":0.23749998211860657,"y":0.5249999761581421},{"x":0.3374999761581421,"y":0.49000000953674316},{"x":0.3174999952316284,"y":0.3424999713897705},{"x":0.4125000238418579,"y":0.28749996423721313},{"x":0.41499996185302734,"y":0.13499996066093445},{"x":0.512499988079071,"y":0.12250000238418579},{"x":0.5225000381469727,"y":0.29249995946884155},{"x":0.6100000143051147,"y":0.3024999797344208},{"x":0.6549999713897705,"y":0.4424999952316284}]}]
    },
    "particleEmitters": [
        {
            "position": "0.23 0.42",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:fire",
                "tint": "hsb 8 75 100"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        },
        {
            "position": "0.35 0.61",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:fire",
                "tint": "hsb 8 75 100"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        }
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/desertSmall/desertSmall.json
{
    "size": 0.5,
    "maxLife": 65,
    "type": "std",
    "price": 800,
    "ability": {
        "type": "teleport",
        "angle": 120,
        "rechargeTime": 4
    },
    "gunSlots": [
        {
            "position": "0.53 0.25",
            "isUnderneathHull": true,
            "allowsRotation": false
        },
        {
            "position": "0.53 0.75",
            "isUnderneathHull": true,
            "allowsRotation": false
        }
    ],
    "displayName": "Beetle",
    "engine": "core:desertEngine",
    "rigidBody": {
        "origin": {
            "x": 0.5378787517547607,
            "y": 0.4943181574344635
        },
        "polygons": [
            [{
                "x": 0.37333327531814575,
                "y": 0.22750002145767212
            }, {
                "x": 0.3766666352748871,
                "y": 0.10416671633720398
            }, {
                "x": 0.4750000238418579,
                "y": 0.022500038146972656
            }, {
                "x": 0.7383333444595337,
                "y": 0.29083335399627686
            }],
            [{
                "x": 0.7366667985916138,
                "y": 0.690833330154419
            }, {
                "x": 0.47833335399627686,
                "y": 0.9541666507720947
            }, {
                "x": 0.3700000047683716,
                "y": 0.87583327293396
            }, {
                "x": 0.37333327531814575,
                "y": 0.7558333873748779
            }],
            [{
                "x": 0.37333327531814575,
                "y": 0.7558333873748779
            }, {
                "x": 0.29666662216186523,
                "y": 0.7174999713897705
            }, {
                "x": 0.2933332920074463,
                "y": 0.2658333480358124
            }, {
                "x": 0.7899999618530273,
                "y": 0.48750001192092896
            }, {
                "x": 0.9933334589004517,
                "y": 0.59416663646698
            }, {
                "x": 0.7366667985916138,
                "y": 0.690833330154419
            }],
            [{
                "x": 0.2933332920074463,
                "y": 0.2658333480358124
            }, {
                "x": 0.37333327531814575,
                "y": 0.22750002145767212
            }, {
                "x": 0.7383333444595337,
                "y": 0.29083335399627686
            }, {
                "x": 0.9850000143051147,
                "y": 0.3891666829586029
            }, {
                "x": 0.7899999618530273,
                "y": 0.48750001192092896
            }],
            [{
                "x": 0.29666662216186523,
                "y": 0.7174999713897705
            }, {
                "x": 0.18666663765907288,
                "y": 0.7774999737739563
            }, {
                "x": 0.04833325743675232,
                "y": 0.6941666603088379
            }, {
                "x": 0.044999927282333374,
                "y": 0.27916669845581055
            }, {
                "x": 0.1899999976158142,
                "y": 0.210833340883255
            }, {
                "x": 0.2933332920074463,
                "y": 0.2658333480358124
            }]
        ],
        "circles": [],
        "shapes": [{
            "type": "POLYGON",
            "vertices": [{
                "x": 0.04833325743675232,
                "y": 0.6941666603088379
            }, {
                "x": 0.044999927282333374,
                "y": 0.27916669845581055
            }, {
                "x": 0.1899999976158142,
                "y": 0.210833340883255
            }, {
                "x": 0.2933332920074463,
                "y": 0.2658333480358124
            }, {
                "x": 0.37333327531814575,
                "y": 0.22750002145767212
            }, {
                "x": 0.3766666352748871,
                "y": 0.10416671633720398
            }, {
                "x": 0.4750000238418579,
                "y": 0.022500038146972656
            }, {
                "x": 0.7383333444595337,
                "y": 0.29083335399627686
            }, {
                "x": 0.9850000143051147,
                "y": 0.3891666829586029
            }, {
                "x": 0.7899999618530273,
                "y": 0.48750001192092896
            }, {
                "x": 0.9933334589004517,
                "y": 0.59416663646698
            }, {
                "x": 0.7366667985916138,
                "y": 0.690833330154419
            }, {
                "x": 0.47833335399627686,
                "y": 0.9541666507720947
            }, {
                "x": 0.3700000047683716,
                "y": 0.87583327293396
            }, {
                "x": 0.37333327531814575,
                "y": 0.7558333873748779
            }, {
                "x": 0.29666662216186523,
                "y": 0.7174999713897705
            }, {
                "x": 0.18666663765907288,
                "y": 0.7774999737739563
            }]
        }]
    },
    "particleEmitters": [
        {
            "position": "0.02 0.46",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:smoke",
                "tint": "fire"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        },
        {
            "position": "0.02 0.54",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:smoke",
                "tint": "fire"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        }
    ]
}

=== MovingBlocks/DestinationSol/modules/kree/assets/ships/kreeMedium/kreeMedium.json
{
    "size": 0.9,
    "maxLife": 70,
    "type": "std",
    "price": 1600,
    "ability": {
        "type": "teleport",
        "angle": 180,
        "rechargeTime": 4
    },
    "displayName": "patrol",
    "engine": "core:desertEngine",
    "gunSlots": [
        {
            "position": "0.2 0.32",
            "isUnderneathHull": false,
            "allowsRotation": true
        },
        {
            "position": "0.2 0.68",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "rigidBody": {"name":"Name","imagePath":"../DestinationSol/modules/empire/assets/ships/empireMedium/empireMedium.png","origin":{"x":0.5,"y":0.5},
"polygons":[[{"x":0.12844036519527435,"y":0.7889907956123352},{"x":0.07339449226856232,"y":0.7431192398071289},{"x":0.07339449226856232,"y":0.5871559381484985},{"x":0.12844036519527435,"y":0.5137614607810974}],[{"x":0.12844036519527435,"y":0.5137614607810974},{"x":0.07339449226856232,"y":0.44954127073287964},{"x":0.08256880939006805,"y":0.29357796907424927},{"x":0.1376146823167801,"y":0.2568807005882263}],[{"x":0.11009174585342407,"y":0.17431187629699707},{"x":0,"y":0.07339447736740112},{"x":0.01834862306714058,"y":0.027522921562194824},{"x":0.1376146823167801,"y":0.027522921562194824}],[{"x":0.1376146823167801,"y":0.027522921562194824},{"x":0.3486238420009613,"y":0.11926603317260742},{"x":0.1376146823167801,"y":0.2568807005882263},{"x":0.11009174585342407,"y":0.17431187629699707}],[{"x":0.8256880640983582,"y":0.8715596199035645},{"x":0.963302731513977,"y":0.8807339072227478},{"x":0.963302731513977,"y":0.9082568883895874},{"x":0.8165137767791748,"y":0.9174311757087708}],[{"x":0.8165137767791748,"y":0.9174311757087708},{"x":0.8440366983413696,"y":0.9541283845901489},{"x":0.6880733966827393,"y":0.9816513657569885},{"x":0.7155963182449341,"y":0.8256880640983582}],[{"x":0.7155963182449341,"y":0.8256880640983582},{"x":0.8165137767791748,"y":0.8348623514175415},{"x":0.8256880640983582,"y":0.8715596199035645},{"x":0.8165137767791748,"y":0.9174311757087708}],[{"x":0.6880733966827393,"y":0.9816513657569885},{"x":0.3669724762439728,"y":0.9816513657569885},{"x":0.302752286195755,"y":0.9357798099517822},{"x":0.6547293663024902,"y":0.7291845083236694},{"x":0.7064220309257507,"y":0.7798165082931519},{"x":0.7155963182449341,"y":0.8256880640983582}],[{"x":0.6547293663024902,"y":0.7291845083236694},{"x":0.7155963182449341,"y":0.7247706055641174},{"x":0.752293586730957,"y":0.7431192398071289},{"x":0.7064220309257507,"y":0.7798165082931519}],[{"x":0.7247706651687622,"y":0.6880733966827393},{"x":0.752293586730957,"y":0.7155963182449341},{"x":0.7155963182449341,"y":0.7247706055641174},{"x":0.6547293663024902,"y":0.7291845083236694}],[{"x":0.302752286195755,"y":0.9357798099517822},{"x":0.6739327311515808,"y":0.3283935487270355},{"x":0.7339449524879456,"y":0.37614673376083374},{"x":0.8165137767791748,"y":0.44954127073287964},{"x":0.8348624110221863,"y":0.5504586696624756},{"x":0.7981651425361633,"y":0.6330274939537048},{"x":0.7247706651687622,"y":0.6880733966827393}],[{"x":0.6739327311515808,"y":0.3283935487270355},{"x":0.7155963182449341,"y":0.33027517795562744},{"x":0.752293586730957,"y":0.3486238121986389},{"x":0.7339449524879456,"y":0.37614673376083374}],[{"x":0.7064220309257507,"y":0.2752293348312378},{"x":0.752293586730957,"y":0.3211008906364441},{"x":0.7155963182449341,"y":0.33027517795562744},{"x":0.6739327311515808,"y":0.3283935487270355}],[{"x":0.302752286195755,"y":0.9357798099517822},{"x":0.12844036519527435,"y":0.853210985660553},{"x":0.12844036519527435,"y":0.7889907956123352},{"x":0.12844036519527435,"y":0.5137614607810974},{"x":0.1376146823167801,"y":0.2568807005882263},{"x":0.7247706651687622,"y":0.2293577790260315},{"x":0.7064220309257507,"y":0.2752293348312378}],[{"x":0.1376146823167801,"y":0.2568807005882263},{"x":0.8256880640983582,"y":0.14678895473480225},{"x":0.8256880640983582,"y":0.1834862232208252},{"x":0.8165137767791748,"y":0.22018343210220337},{"x":0.7247706651687622,"y":0.2293577790260315}],[{"x":0.8256880640983582,"y":0.14678895473480225},{"x":0.963302731513977,"y":0.14678895473480225},{"x":0.963302731513977,"y":0.17431187629699707},{"x":0.8256880640983582,"y":0.1834862232208252}],[{"x":0.1376146823167801,"y":0.2568807005882263},{"x":0.3486238420009613,"y":0.11926603317260742},{"x":0.4403669834136963,"y":0.064220130443573},{"x":0.7155963182449341,"y":0.07339447736740112},{"x":0.8623853325843811,"y":0.11926603317260742},{"x":0.8256880640983582,"y":0.14678895473480225}],[{"x":0.302752286195755,"y":0.9357798099517822},{"x":0.03669724613428116,"y":1.0550458431243896},{"x":0.00917431153357029,"y":1.0091742277145386},{"x":0.00917431153357029,"y":0.963302731513977},{"x":0.12844036519527435,"y":0.853210985660553}]],"circles":[],"shapes":[{"type":"POLYGON","vertices":[{"x":0.03669724613428116,"y":1.0550458431243896},{"x":0.302752286195755,"y":0.9357798099517822},{"x":0.3669724762439728,"y":0.9816513657569885},{"x":0.6880733966827393,"y":0.9816513657569885},{"x":0.8440366983413696,"y":0.9541283845901489},{"x":0.8165137767791748,"y":0.9174311757087708},{"x":0.963302731513977,"y":0.9082568883895874},{"x":0.963302731513977,"y":0.8807339072227478},{"x":0.8256880640983582,"y":0.8715596199035645},{"x":0.8165137767791748,"y":0.8348623514175415},{"x":0.7155963182449341,"y":0.8256880640983582},{"x":0.7064220309257507,"y":0.7798165082931519},{"x":0.752293586730957,"y":0.7431192398071289},{"x":0.7155963182449341,"y":0.7247706055641174},{"x":0.752293586730957,"y":0.7155963182449341},{"x":0.7247706651687622,"y":0.6880733966827393},{"x":0.7981651425361633,"y":0.6330274939537048},{"x":0.8348624110221863,"y":0.5504586696624756},{"x":0.8165137767791748,"y":0.44954127073287964},{"x":0.7339449524879456,"y":0.37614673376083374},{"x":0.752293586730957,"y":0.3486238121986389},{"x":0.7155963182449341,"y":0.33027517795562744},{"x":0.752293586730957,"y":0.3211008906364441},{"x":0.7064220309257507,"y":0.2752293348312378},{"x":0.7247706651687622,"y":0.2293577790260315},{"x":0.8165137767791748,"y":0.22018343210220337},{"x":0.8256880640983582,"y":0.1834862232208252},{"x":0.963302731513977,"y":0.17431187629699707},{"x":0.963302731513977,"y":0.14678895473480225},{"x":0.8256880640983582,"y":0.14678895473480225},{"x":0.8623853325843811,"y":0.11926603317260742},{"x":0.7155963182449341,"y":0.07339447736740112},{"x":0.4403669834136963,"y":0.064220130443573},{"x":0.3486238420009613,"y":0.11926603317260742},{"x":0.1376146823167801,"y":0.027522921562194824},{"x":0.01834862306714058,"y":0.027522921562194824},{"x":0,"y":0.07339447736740112},{"x":0.11009174585342407,"y":0.17431187629699707},{"x":0.1376146823167801,"y":0.2568807005882263},{"x":0.08256880939006805,"y":0.29357796907424927},{"x":0.07339449226856232,"y":0.44954127073287964},{"x":0.12844036519527435,"y":0.5137614607810974},{"x":0.07339449226856232,"y":0.5871559381484985},{"x":0.07339449226856232,"y":0.7431192398071289},{"x":0.12844036519527435,"y":0.7889907956123352},{"x":0.12844036519527435,"y":0.853210985660553},{"x":0.00917431153357029,"y":0.963302731513977},{"x":0.00917431153357029,"y":1.0091742277145386}]}]},
    "particleEmitters": [
        {
            "position": "0.02 0.31",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:smoke",
                "tint": "fire"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        },
        {
            "position": "0.02 0.69",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:smoke",
                "tint": "fire"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        }
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/desertOrbiter/desertOrbiter.json
{
    "size": 0.41,
    "maxLife": 54,
    "type": "std",
    "price": 600,
    "hirePrice": 1000,
    "ability": {
        "type": "teleport",
        "angle": 90,
        "rechargeTime": 4
    },
    "displayName": "Bomber",
    "engine": "core:desertEngine",
    "gunSlots": [
        {
            "position": "0.32 0.32",
            "isUnderneathHull": false,
            "allowsRotation": false
        }
    ],
    "rigidBody": {
       "origin":{"x":0.4583333730697632,"y":0.5056817531585693},"polygons":[[{"x":0.7975000143051147,"y":0.6050000190734863},{"x":0.9800000786781311,"y":0.6450000405311584},{"x":0.7674999833106995,"y":0.8850000500679016}],[{"x":0.7674999833106995,"y":0.8850000500679016},{"x":0.4650000333786011,"y":0.9175000190734863},{"x":0.20500001311302185,"y":0.9300000667572021},{"x":0.032499998807907104,"y":0.7725000381469727},{"x":0.034999996423721313,"y":0.18999996781349182}],[{"x":0.034999996423721313,"y":0.18999996781349182},{"x":0.22749999165534973,"y":0.07749998569488525},{"x":0.44749999046325684,"y":0.07999995350837708},{"x":0.8000000715255737,"y":0.1525000035762787},{"x":0.7975000143051147,"y":0.6050000190734863},{"x":0.7674999833106995,"y":0.8850000500679016}]],"circles":[],"shapes":[{"type":"POLYGON","vertices":[{"x":0.9800000786781311,"y":0.6450000405311584},{"x":0.7674999833106995,"y":0.8850000500679016},{"x":0.4650000333786011,"y":0.9175000190734863},{"x":0.20500001311302185,"y":0.9300000667572021},{"x":0.032499998807907104,"y":0.7725000381469727},{"x":0.034999996423721313,"y":0.18999996781349182},{"x":0.22749999165534973,"y":0.07749998569488525},{"x":0.44749999046325684,"y":0.07999995350837708},{"x":0.8000000715255737,"y":0.1525000035762787},{"x":0.7975000143051147,"y":0.6050000190734863}]}]
    },
    "particleEmitters": [
        {
            "position": "0 0.33",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:smoke",
                "tint": "fire"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        },
        {
            "position": "0 0.67",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.07,
                "tex": "core:smoke",
                "tint": "fire"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        }
    ]
}
