=== MovingBlocks/DestinationSol/engine/src/main/resources/assets/schemas/schemaHullConfig.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Describes ship configuration, that is size, health and positions of effect or functional elements. Also describes physical shape of ship.",
  "type": "object",
  "required": [
    "size",
    "maxLife",
    "type",
    "rigidBody",
    "gunSlots"
  ],
  "properties": {
    "size": {
      "type": "number",
      "exclusiveMinimum": 0,
      "description": "Multiplier of ship size in magical units. Common values are between 0.2 (tiny ships) and 5 (huge ships)."
    },
    "maxLife": {
      "type": "integer",
      "description": "Default and maximum achievable life of ship."
    },
    "lightSrcPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Positions of light sources (graphical effect)"
    },
    "forceBeaconPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Beacons - things on ships and stations that attract other ships from close enough range ('docking ports')"
    },
    "doorPoss": {
      "$ref": "#/definitions/vec2List",
      "description": "Positions of door centers on ships - doors are horizontal things opening on other ship proximity."
    },
    "type": {
      "type": "string",
      "enum": [
        "std",
        "big",
        "station"
      ],
      "description": "Denotes whether ship is standard or big size, or if it is a station"
    },
    "engine": {
      "type": "string",
      "description": "Id of the engine on the ship",
      "pattern": "^\\w+:\\w+$"
    },
    "ability": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Type of ship's ability - one of 'sloMo', 'knockBack', 'teleport', 'emWave', 'unShield'"
        },
        "rechargeTime": {
          "type": "number",
          "minimum": 0,
          "description": "Recharge time of ability in seconds."
        }
      },
      "anyOf": [
        {
          "properties": {
            "type": {
              "enum": [
                "sloMo"
              ]
            },
            "factor": {
              "type": "number",
              "description": "Multiplier of time speed - 1 is normal speed, lower values slow down time, higher speed up time."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "teleport"
              ]
            },
            "angle": {
              "type": "number"
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "knockBack"
              ]
            },
            "force": {
              "type": "number",
              "description": "Denotes how hard everything within radius is pushed away."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "emWave"
              ]
            },
            "duration": {
              "type": "number",
              "description": "For how long controls of ships in range will be disabled, in seconds."
            }
          }
        },
        {
          "properties": {
            "type": {
              "enum": [
                "unShield"
              ]
            },
            "amount": {
              "type": "number",
              "description": "Damage to deal to enemy shields."
            }
          }
        }
      ]
    },
    "displayName": {
      "type": "string",
      "description": "Human friendly name of the ship"
    },
    "price": {
      "type": "number",
      "description": "Price for buying this ship in shop"
    },
    "hirePrice": {
      "type": "number",
      "description": "Price for hiring this ship as mercenary"
    },
    "rigidBody": {
      "description": "Physical model of ship's body. This is meant to be exported from some utility application (b2dEditor",
      "type": "object",
      "properties": {
        "origin": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ]
        },
        "polygons": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "x": {
                  "type": "number"
                },
                "y": {
                  "type": "number"
                }
              }
            }
          }
        },
        "shapes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              }
            }
          }
        },
        "circles": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "cx": {
                "type": "number"
              },
              "cy": {
                "type": "number"
              },
              "r": {
                "type": "number"
              }
            }
          }
        }
      },
      "required": [
        "origin",
        "polygons",
        "shapes",
        "circles"
      ]
    },
    "gunSlots": {
      "type": "array",
      "items": {
        "type": "object",
        "minItems": 1,
        "maxItems": 2,
        "properties": {
          "position": {
            "$ref": "#/definitions/vec2"
          },
          "isUnderneathHull": {
            "type": "boolean"
          },
          "allowsRotation": {
            "type": "boolean"
          }
        },
        "required": [
          "position"
        ]
      }
    },
    "particleEmitters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "position": {
            "$ref": "#/definitions/vec2"
          },
          "trigger": {
            "type": "string"
          },
          "angleOffset": {
            "type": "number"
          },
          "hasLight": {
            "type": "boolean"
          },
          "particle": {
            "type": "object",
            "required": [
              "effectFile",
              "tex",
              "tint"
            ],
            "properties": {
              "effectFile": {
                "type": "string",
                "pattern": "^\\w+:\\w+$"
              },
              "size": {
                "type": "number"
              },
              "tex": {
                "type": "string",
                "pattern": "^\\w+:\\w+$"
              },
              "floatsUp": {
                "type": "boolean"
              },
              "tint": {
                "type": "string",
                "pattern": "^(\\w+|(hsb (((360)|(3[0-5]\\d)|([012]?\\d?\\d))( ((100)|\\d?\\d)){2})|(((([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5])) ){2}(([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5]))))( (([01]?\\d?\\d)|(2[0-4]\\d)|(25[0-5])))?)$"
              }
            }
          },
          "workSounds": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^\\w+:\\w+$"
            }
          }
        },
        "required": [
          "position",
          "trigger",
          "particle"
        ]
      }
    }
  },
  "definitions": {
    "vec2": {
      "type": "string",
      "pattern": "^(([0-9]*\\.)?[0-9]+ +([0-9]*\\.)?[0-9]+)$",
      "$comment": "2 float values separated by one or more spaces, ints also accepted"
    },
    "vec2List": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/vec2"
      }
    }
  }
}

=== MovingBlocks/DestinationSol/modules/salvage/assets/ships/station/station.json
{
    "size": 8,
    "maxLife": 400,
    "type": "station",
    "gunSlots": [
        {
            "position": "0.79 0.7",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "lightSrcPoss": [
        ".26 .93",
        ".73 .93"
    ],
    "forceBeaconPoss": [
        "0.185 0.756"
    ],
   "rigidBody": {
        "origin": {
            "x": 0.5075757503509521,
            "y": 0.5359848737716675
        },
        "polygons":[
            [
               {
                  "x":0.25499996542930603,
                  "y":0.8687499761581421
               },
               {
                  "x":0.16749992966651917,
                  "y":0.8687499761581421
               },
               {
                  "x":0.16499993205070496,
                  "y":0.6912500858306885
               },
               {
                  "x":0.19749993085861206,
                  "y":0.6187500357627869
               }
            ],
            [
               {
                  "x":0.19749993085861206,
                  "y":0.6187500357627869
               },
               {
                  "x":0.16249996423721313,
                  "y":0.581250011920929
               },
               {
                  "x":0.15999993681907654,
                  "y":0.5387499928474426
               },
               {
                  "x":0.20249995589256287,
                  "y":0.5387499928474426
               }
            ],
            [
               {
                  "x":0.690000057220459,
                  "y":0.3662499785423279
               },
               {
                  "x":0.7025001049041748,
                  "y":0.02124994993209839
               },
               {
                  "x":0.8500001430511475,
                  "y":0.02374991774559021
               },
               {
                  "x":0.9575001001358032,
                  "y":0.13374999165534973
               },
               {
                  "x":0.9525001049041748,
                  "y":0.7137500643730164
               }
            ],
            [
               {
                  "x":0.9525001049041748,
                  "y":0.7137500643730164
               },
               {
                  "x":0.8475000858306885,
                  "y":0.8212500214576721
               },
               {
                  "x":0.625,
                  "y":0.8187500238418579
               },
               {
                  "x":0.6525000333786011,
                  "y":0.38874998688697815
               },
               {
                  "x":0.690000057220459,
                  "y":0.3662499785423279
               }
            ],
            [
               {
                  "x":0.625,
                  "y":0.8187500238418579
               },
               {
                  "x":0.39499998092651367,
                  "y":0.90625
               },
               {
                  "x":0.3125,
                  "y":0.90625
               },
               {
                  "x":0.25499996542930603,
                  "y":0.8687499761581421
               },
               {
                  "x":0.19749993085861206,
                  "y":0.6187500357627869
               },
               {
                  "x":0.20249995589256287,
                  "y":0.5387499928474426
               },
               {
                  "x":0.34999996423721313,
                  "y":0.38624998927116394
               },
               {
                  "x":0.6525000333786011,
                  "y":0.38874998688697815
               }
            ],
            [
               {
                  "x":0.625,
                  "y":0.8187500238418579
               },
               {
                  "x":0.5749999284744263,
                  "y":0.96875
               },
               {
                  "x":0.41999995708465576,
                  "y":0.971250057220459
               },
               {
                  "x":0.39499998092651367,
                  "y":0.90625
               }
            ]
         ],
         "circles":[

         ],
         "shapes":[
            {
               "type":"POLYGON",
               "vertices":[
                  {
                     "x":0.41999995708465576,
                     "y":0.971250057220459
                  },
                  {
                     "x":0.5749999284744263,
                     "y":0.96875
                  },
                  {
                     "x":0.625,
                     "y":0.8187500238418579
                  },
                  {
                     "x":0.8475000858306885,
                     "y":0.8212500214576721
                  },
                  {
                     "x":0.9525001049041748,
                     "y":0.7137500643730164
                  },
                  {
                     "x":0.9575001001358032,
                     "y":0.13374999165534973
                  },
                  {
                     "x":0.8500001430511475,
                     "y":0.02374991774559021
                  },
                  {
                     "x":0.7025001049041748,
                     "y":0.02124994993209839
                  },
                  {
                     "x":0.690000057220459,
                     "y":0.3662499785423279
                  },
                  {
                     "x":0.6525000333786011,
                     "y":0.38874998688697815
                  },
                  {
                     "x":0.34999996423721313,
                     "y":0.38624998927116394
                  },
                  {
                     "x":0.20249995589256287,
                     "y":0.5387499928474426
                  },
                  {
                     "x":0.15999993681907654,
                     "y":0.5387499928474426
                  },
                  {
                     "x":0.16249996423721313,
                     "y":0.581250011920929
                  },
                  {
                     "x":0.19749993085861206,
                     "y":0.6187500357627869
                  },
                  {
                     "x":0.16499993205070496,
                     "y":0.6912500858306885
                  },
                  {
                     "x":0.16749992966651917,
                     "y":0.8687499761581421
                  },
                  {
                     "x":0.25499996542930603,
                     "y":0.8687499761581421
                  },
                  {
                     "x":0.3125,
                     "y":0.90625
                  },
                  {
                     "x":0.39499998092651367,
                     "y":0.90625
                  }
               ]
            }
         ]
    }
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/bus/bus.json
{
    "size": 3.5,
    "maxLife": 120,
    "type": "big",
    "gunSlots": [
        {
            "position": "0.64 0.5",
            "isUnderneathHull": false,
            "allowsRotation": true
        },
        {
            "position": "0.36 0.5",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "forceBeaconPoss": [
        "0.5 0.25",
        "0.5 0.75"
    ],
    "doorPoss": [
        "0.5 0.13",
        "0.5 0.87"
    ],
    "engine": "core:imperialBigEngine",
    "rigidBody": {
       "origin":{"x":0.48249998688697815,"y":0.48374998569488525},"polygons":[[{"x":0.7275000214576721,"y":0.7450000047683716},{"x":0.7225000262260437,"y":0.8725000023841858},{"x":0.2774999737739563,"y":0.8700000047683716},{"x":0.26749998331069946,"y":0.7000000476837158}],[{"x":0.26749998331069946,"y":0.7000000476837158},{"x":0.1925000250339508,"y":0.76500004529953},{"x":0.06999999284744263,"y":0.6775000095367432},{"x":0.06999999284744263,"y":0.3199999928474426},{"x":0.1824999749660492,"y":0.23749995231628418},{"x":0.27000001072883606,"y":0.29749995470046997}],[{"x":0.7325000762939453,"y":0.2499999701976776},{"x":0.9000000953674316,"y":0.2524999678134918},{"x":0.8875000476837158,"y":0.7400000095367432},{"x":0.7275000214576721,"y":0.7450000047683716}],[{"x":0.7275000214576721,"y":0.7450000047683716},{"x":0.26749998331069946,"y":0.7000000476837158},{"x":0.27000001072883606,"y":0.29749995470046997},{"x":0.2749999761581421,"y":0.1274999976158142},{"x":0.7325000762939453,"y":0.12999996542930603},{"x":0.7325000762939453,"y":0.2499999701976776}]],"circles":[],"shapes":[{"type":"POLYGON","vertices":[{"x":0.7275000214576721,"y":0.7450000047683716},{"x":0.7225000262260437,"y":0.8725000023841858},{"x":0.2774999737739563,"y":0.8700000047683716},{"x":0.26749998331069946,"y":0.7000000476837158},{"x":0.1925000250339508,"y":0.76500004529953},{"x":0.06999999284744263,"y":0.6775000095367432},{"x":0.06999999284744263,"y":0.3199999928474426},{"x":0.1824999749660492,"y":0.23749995231628418},{"x":0.27000001072883606,"y":0.29749995470046997},{"x":0.2749999761581421,"y":0.1274999976158142},{"x":0.7325000762939453,"y":0.12999996542930603},{"x":0.7325000762939453,"y":0.2499999701976776},{"x":0.9000000953674316,"y":0.2524999678134918},{"x":0.8875000476837158,"y":0.7400000095367432}]}]
    },
    "particleEmitters": [
        {
            "position": "0.09 0.38",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.3,
                "tex": "core:fire",
                "tint": "hsb 140 20 65"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        },
        {
            "position": "0.09 0.62",
            "trigger": "engine",
            "hasLight": true,
            "particle": {
                "effectFile": "core:flame",
                "size": 0.3,
                "tex": "core:fire",
                "tint": "hsb 140 20 65"
            },
            "workSounds": [
                "core:medEngineWork0",
                "core:medEngineWork1",
                "core:medEngineWork2",
                "core:medEngineWork3",
                "core:medEngineWork4"
            ]
        }
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/ships/techiePlanetTurret/techiePlanetTurretProperties.json
{
    "size": 1.7,
    "maxLife": 75,
    "type": "station",
    "gunSlots": [
        {
            "position": "0.5 0.14",
            "isUnderneathHull": false,
            "allowsRotation": true
        },
        {
            "position": "0.5 0.38",
            "isUnderneathHull": false,
            "allowsRotation": true
        }
    ],
    "lightSrcPoss": [
        ".47 .01"
    ],
    "rigidBody": {
        "origin": {
            "x": 0.5050000548362732,
            "y": 0.7112500071525574
        },
        "polygons": [
            [
                {
                    "x": 0.21500001847743988,
                    "y": 0.35187503695487976
                },
                {
                    "x": 0.23749999701976776,
                    "y": 0.37187501788139343
                },
                {
                    "x": 0.08624998480081558,
                    "y": 0.5293750166893005
                },
                {
                    "x": 0.0637500062584877,
                    "y": 0.5043750405311584
                }
            ],
            [
                {
                    "x": 0.7887499928474426,
                    "y": 0.35062500834465027
                },
                {
                    "x": 0.9399999976158142,
                    "y": 0.503125011920929
                },
                {
                    "x": 0.9174999594688416,
                    "y": 0.5268750190734863
                },
                {
                    "x": 0.7662500143051147,
                    "y": 0.37187501788139343
                }
            ],
            [
                {
                    "x": 0.8637500405311584,
                    "y": 0.2718750238418579
                },
                {
                    "x": 0.7950000166893005,
                    "y": 0.34062501788139343
                },
                {
                    "x": 0.20749999582767487,
                    "y": 0.34187501668930054
                },
                {
                    "x": 0.13625000417232513,
                    "y": 0.2631250321865082
                }
            ],
            [
                {
                    "x": 0.5387500524520874,
                    "y": 0.3243750333786011
                },
                {
                    "x": 0.5287500023841858,
                    "y": 0.5731250047683716
                },
                {
                    "x": 0.4675000011920929,
                    "y": 0.5718750357627869
                },
                {
                    "x": 0.4612500071525574,
                    "y": 0.3318750262260437
                }
            ]
        ],
        "circles": [
            {
                "cx": 0.5049999952316284,
                "cy": 0.7341667413711548,
                "r": 0.17288410663604736
            },
            {
                "cx": 0.6483333706855774,
                "cy": 0.5441666841506958,
                "r": 0.04737560451030731
            },
            {
                "cx": 0.7450000047683716,
                "cy": 0.7325000166893005,
                "r": 0.05459454283118248
            },
            {
                "cx": 0.258333295583725,
                "cy": 0.7341667413711548,
                "r": 0.05520165339112282
            },
            {
                "cx": 0.35499998927116394,
                "cy": 0.5425000190734863,
                "r": 0.04693375900387764
            },
            {
                "cx": 0.6449999809265137,
                "cy": 0.9212499260902405,
                "r": 0.046703923493623734
            },
            {
                "cx": 0.36250004172325134,
                "cy": 0.9237499833106995,
                "r": 0.050559353083372116
            }
        ],
        "shapes": [
            {
                "type": "CIRCLE",
                "vertices": [
                    {
                        "x": 0.5049999952316284,
                        "y": 0.7341667413711548
                    },
                    {
                        "x": 0.6483333706855774,
                        "y": 0.637499988079071
                    }
                ]
            },
            {
                "type": "CIRCLE",
                "vertices": [
                    {
                        "x": 0.6483333706855774,
                        "y": 0.5441666841506958
                    },
                    {
                        "x": 0.6850000619888306,
                        "y": 0.5141666531562805
                    }
                ]
            },
            {
                "type": "CIRCLE",
                "vertices": [
                    {
                        "x": 0.7450000047683716,
                        "y": 0.7325000166893005
                    },
                    {
                        "x": 0.7916667461395264,
                        "y": 0.7041666507720947
                    }
                ]
            },
            {
                "type": "CIRCLE",
                "vertices": [
                    {
                        "x": 0.258333295583725,
                        "y": 0.7341667413711548
                    },
                    {
                        "x": 0.30666661262512207,
                        "y": 0.7075000405311584
                    }
                ]
            },
            {
                "type": "CIRCLE",
                "vertices": [
                    {
                        "x": 0.35499998927116394,
                        "y": 0.5425000190734863
                    },
                    {
                        "x": 0.3999999761581421,
                        "y": 0.5291666388511658
                    }
                ]
            },
            {
                "type": "CIRCLE",
                "vertices": [
                    {
                        "x": 0.6449999809265137,
                        "y": 0.9212499260902405
                    },
                    {
                        "x": 0.690000057220459,
                        "y": 0.9087499380111694
                    }
                ]
            },
            {
                "type": "CIRCLE",
                "vertices": [
                    {
                        "x": 0.36250004172325134,
                        "y": 0.9237499833106995
                    },
                    {
                        "x": 0.4125000238418579,
                        "y": 0.9162499904632568
                    }
                ]
            },
            {
                "type": "POLYGON",
                "vertices": [
                    {
                        "x": 0.0637500062584877,
                        "y": 0.5043750405311584
                    },
                    {
                        "x": 0.08624998480081558,
                        "y": 0.5293750166893005
                    },
                    {
                        "x": 0.23749999701976776,
                        "y": 0.37187501788139343
                    },
                    {
                        "x": 0.21500001847743988,
                        "y": 0.35187503695487976
                    }
                ]
            },
            {
                "type": "POLYGON",
                "vertices": [
                    {
                        "x": 0.7662500143051147,
                        "y": 0.37187501788139343
                    },
                    {
                        "x": 0.9174999594688416,
                        "y": 0.5268750190734863
                    },
                    {
                        "x": 0.9399999976158142,
                        "y": 0.503125011920929
                    },
                    {
                        "x": 0.7887499928474426,
                        "y": 0.35062500834465027
                    }
                ]
            },
            {
                "type": "POLYGON",
                "vertices": [
                    {
                        "x": 0.13625000417232513,
                        "y": 0.2631250321865082
                    },
                    {
                        "x": 0.20749999582767487,
                        "y": 0.34187501668930054
                    },
                    {
                        "x": 0.7950000166893005,
                        "y": 0.34062501788139343
                    },
                    {
                        "x": 0.8637500405311584,
                        "y": 0.2718750238418579
                    }
                ]
            },
            {
                "type": "POLYGON",
                "vertices": [
                    {
                        "x": 0.4612500071525574,
                        "y": 0.3318750262260437
                    },
                    {
                        "x": 0.4675000011920929,
                        "y": 0.5718750357627869
                    },
                    {
                        "x": 0.5287500023841858,
                        "y": 0.5731250047683716
                    },
                    {
                        "x": 0.5387500524520874,
                        "y": 0.3243750333786011
                    }
                ]
            }
        ]
    }
}
