=== MovingBlocks/DestinationSol/engine/src/main/resources/assets/schemas/schemaGun.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Guns are the primary weapons for ships",
  "type": "object",
  "required": [
    "maxAngleVar",
    "angleVarDamp",
    "angleVarPerShot",
    "timeBetweenShots",
    "reloadTime",
    "price",
    "clipName",
    "gunLength",
    "displayName",
    "shootSounds",
    "reloadSounds"
  ],
  "properties": {
    "maxAngleVar": {
      "type": "integer",
      "minimum": 0,
      "description": "Maximum angle variation for a shot from the center of the gun"
    },
    "angleVarDamp": {
      "type": "integer",
      "minimum": 0,
      "description": "Puts a damper or delay on the angle variation"
    },
    "angleVarPerShot": {
      "type": "integer",
      "minimum": 0,
      "description": "Controls how much the angle of the bullet can vary from shot to shot"
    },
    "timeBetweenShots": {
      "type": "number",
      "minimum": 0,
      "description": "Controls how fast the gun fires"
    },
    "reloadTime": {
      "type": "number",
      "minimum": 0,
      "description": "Amount of time in seconds it takes for the gun to reload"
    },
    "price": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "description": "Amount the gun costs to buy at a station"
    },
    "clipName": {
      "type": "string",
      "pattern": "^\\w+:\\w+$",
      "description": "Module path of the clip the gun uses to fire"
    },
    "gunLength": {
      "type": "number",
      "exclusiveMinimum": 0,
      "description": "Multiplier used to scale the gun length"
    },
    "displayName": {
      "type": "string",
      "minLength": 1,
      "description": "Name to be displayed in inventories and trading stations"
    },
    "shootSounds": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\w+:\\w+$"
      },
      "description": "An array to iterate over when firing the gun for audio assets to be played"
    },
    "reloadSounds": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\w+:\\w+$"
      },
      "description": "An array to iterate over when reloading the gun for audio assets to be played"
    },
    "fixed": {
      "type": "boolean",
      "description": "Controls whether the gun is fixed in place"
    },
    "texLenPerc": {
      "type": "number",
      "description": "Multiplier to scale the length of the projetile's texture"
    },
    "lightOnShot": {
      "type": "boolean",
      "description": "Whether the gun should show a light at the muzzle when it fires"
    }
  }
}

=== MovingBlocks/DestinationSol/modules/core/assets/items/guns/fixedGun/fixedGun.json
{
    "fixed": true,
    "maxAngleVar": 10,
    "angleVarDamp": 6,
    "angleVarPerShot": 1,
    "timeBetweenShots": 0.07,
    "reloadTime": 2,
    "price": 220,
    "clipName": "core:bulletClip",
    "gunLength": 0.18,
    "displayName": "Heavy Machine Gun",
    "lightOnShot": true,
    "shootSounds": [
        "core:fixedGunShoot0",
        "core:fixedGunShoot1"
    ],
    "reloadSounds": [
        "core:fixedGunReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/mechanical/assets/items/guns/MechGun/mechGun.json
{
    "fixed": false,
    "maxAngleVar": 3,
    "angleVarDamp": 6,
    "angleVarPerShot": 3,
    "timeBetweenShots": 0.07,
    "reloadTime": 1.5,
    "price": 350,
    "clipName": "core:plasmaClip",
    "gunLength": 0.45,
    "displayName": "Mech Gun",
    "lightOnShot": true,
    "shootSounds": [
        "core:shotGunShoot"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/vulcan/assets/items/guns/electric/electric.json
{
  "fixed": false,
  "maxAngleVar": 0,
  "angleVarDamp": 0,
  "angleVarPerShot": 0,
  "timeBetweenShots": 1,
  "reloadTime": 0.1,
  "price": 1000000,
  "clipName": "vulcan:electricClip",
  "gunLength": 0.5,
  "displayName": "electric",
  "lightOnShot": true,
  "shootSounds": [
    "core:waveGun"
  ],
  "reloadSounds": [
    "core:gunReload"
  ]
}

=== MovingBlocks/DestinationSol/modules/slimey/assets/items/guns/slimeThrowerBetter/slimeThrowerBetter.json
{
  "maxAngleVar": 0,
  "angleVarDamp": 0,
  "angleVarPerShot": 0,
  "timeBetweenShots": 0.05,
  "reloadTime": 1,
  "price": 2000,
  "clipName": "slimey:slimeClipBetter",
  "gunLength": 0.2,
  "texLenPerc": 0.85,
  "displayName": "Better Slime Thrower",
  "lightOnShot": false,
  "shootSounds": [
    "slimey:shootSplat"
  ],
  "reloadSounds": [
    "core:gunReload"
  ]
}

=== MovingBlocks/DestinationSol/modules/kree/assets/items/guns/destroyer/destroyer.json
{
    "fixed": false,
    "maxAngleVar": 30,
    "angleVarDamp": 6,
    "angleVarPerShot": 3,
    "timeBetweenShots": 0.6,
    "reloadTime": 0.5,
    "price": 3000,
    "clipName": "core:missileClip",
    "gunLength": 0.2,
    "texLenPerc": 0.87,
    "displayName": "destroyer",
    "shootSounds": [
        "core:rocketLauncherShoot"
    ],
    "reloadSounds": [
        "core:rocketLauncherReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/items/guns/missileLauncher/missileLauncher.json
{
    "fixed": true,
    "maxAngleVar": 30,
    "angleVarDamp": 6,
    "angleVarPerShot": 3,
    "timeBetweenShots": 1.1,
    "reloadTime": 2.5,
    "price": 300,
    "clipName": "core:missileClip",
    "gunLength": 0.2,
    "texLenPerc": 0.87,
    "displayName": "Missile Launcher",
    "shootSounds": [
        "core:rocketLauncherShoot"
    ],
    "reloadSounds": [
        "core:rocketLauncherReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/caution/assets/items/guns/cautionMachine/cautionMachine.json
{
    "maxAngleVar": 10,
    "angleVarDamp": 6,
    "angleVarPerShot": 2,
    "timeBetweenShots": 0.1,
    "reloadTime": 0.5,
    "price": 800,
    "clipName": "core:plasmaClip",
    "gunLength": 0.26,
    "texLenPerc": 0.87,
    "displayName": "Plasma Machine Gun",
    "lightOnShot": true,
    "shootSounds": [
        "core:waveGun"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/items/guns/cannon/cannon.json
{
    "maxAngleVar": 10,
    "angleVarDamp": 6,
    "angleVarPerShot": 1,
    "timeBetweenShots": 1.8,
    "reloadTime": 2.5,
    "price": 600,
    "clipName": "core:slugClip",
    "gunLength": 0.24,
    "texLenPerc": 0.85,
    "displayName": "Cannon",
    "lightOnShot": true,
    "shootSounds": [
        "core:cannonShoot"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}
