=== MovingBlocks/DestinationSol/engine/src/main/resources/assets/schemas/schemaGun.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Guns are the primary weapons for ships",
  "type": "object",
  "required": [
    "maxAngleVar",
    "angleVarDamp",
    "angleVarPerShot",
    "timeBetweenShots",
    "reloadTime",
    "price",
    "clipName",
    "gunLength",
    "displayName",
    "shootSounds",
    "reloadSounds"
  ],
  "properties": {
    "maxAngleVar": {
      "type": "integer",
      "minimum": 0,
      "description": "Maximum angle variation for a shot from the center of the gun"
    },
    "angleVarDamp": {
      "type": "integer",
      "minimum": 0,
      "description": "Puts a damper or delay on the angle variation"
    },
    "angleVarPerShot": {
      "type": "integer",
      "minimum": 0,
      "description": "Controls how much the angle of the bullet can vary from shot to shot"
    },
    "timeBetweenShots": {
      "type": "number",
      "minimum": 0,
      "description": "Controls how fast the gun fires"
    },
    "reloadTime": {
      "type": "number",
      "minimum": 0,
      "description": "Amount of time in seconds it takes for the gun to reload"
    },
    "price": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "description": "Amount the gun costs to buy at a station"
    },
    "clipName": {
      "type": "string",
      "pattern": "^\\w+:\\w+$",
      "description": "Module path of the clip the gun uses to fire"
    },
    "gunLength": {
      "type": "number",
      "exclusiveMinimum": 0,
      "description": "Multiplier used to scale the gun length"
    },
    "displayName": {
      "type": "string",
      "minLength": 1,
      "description": "Name to be displayed in inventories and trading stations"
    },
    "shootSounds": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\w+:\\w+$"
      },
      "description": "An array to iterate over when firing the gun for audio assets to be played"
    },
    "reloadSounds": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\w+:\\w+$"
      },
      "description": "An array to iterate over when reloading the gun for audio assets to be played"
    },
    "fixed": {
      "type": "boolean",
      "description": "Controls whether the gun is fixed in place"
    },
    "texLenPerc": {
      "type": "number",
      "description": "Multiplier to scale the length of the projetile's texture"
    },
    "lightOnShot": {
      "type": "boolean",
      "description": "Whether the gun should show a light at the muzzle when it fires"
    }
  }
}

=== MovingBlocks/DestinationSol/modules/deepspace/assets/items/guns/alienGun/alienGun.json
{
    "maxAngleVar": 10,
    "angleVarDamp": 6,
    "angleVarPerShot": 1,
    "timeBetweenShots": 0.13,
    "reloadTime": 1,
    "price": 120,
    "clipName": "deepspace:alienbulletClip",
    "gunLength": 0.16,
    "texLenPerc": 0.7,
    "displayName": "Alien Gun",
    "lightOnShot": true,
    "shootSounds": [
        "core:waveGun"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/core/assets/items/guns/waveGun/waveGun.json
{
    "maxAngleVar": 30,
    "angleVarDamp": 6,
    "angleVarPerShot": 2,
    "timeBetweenShots": 0.8,
    "reloadTime": 2.5,
    "price": 1000,
    "clipName": "core:waveClip",
    "gunLength": 0.26,
    "texLenPerc": 0.87,
    "displayName": "Wave Gun",
    "lightOnShot": true,
    "shootSounds": [
        "core:waveGun"
    ],
    "reloadSounds": [
        "core:gunReload"
    ]
}

=== MovingBlocks/DestinationSol/modules/formic/assets/items/guns/gryazevShipunov/gryazevShipunov.json
{
    "fixed": true,
    "maxAngleVar": 2,
    "angleVarDamp": 10,
    "angleVarPerShot": 1,
    "timeBetweenShots": 0.02,
    "reloadTime": 1,
    "price": 500,
    "clipName": "formic:uraniumClip",
    "gunLength": 0.25,
    "displayName": "Gryazev Shipunov",
    "lightOnShot": true,
    "shootSounds": [
        "core:fixedGunShoot0",
        "core:fixedGunShoot1"
    ],
    "reloadSounds": [
        "core:fixedGunReload"
    ]
}
